version: '3.8'
services:
  zipkin-server:
    image: openzipkin/zipkin:2.23.16
    ports:
      - "9411:9411"
    networks:
      - spring-network
  cambio-db:
    image: mysql:8
    restart: always
    ports:
      - '3308:3308'
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_DATABASE=cambio_service
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_TCP_PORT=3308
    volumes:
      - db-data-cambio:/var/lib/mysql
    networks:
      - spring-network
  book-db:
    image: mysql:8
    restart: always
    ports:
      - '3310:3310'
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_DATABASE=book_service
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_TCP_PORT=3310
    volumes:
      - db-data-book:/var/lib/mysql
    networks:
      - spring-network
  naming-server:
    image: daiven75/naming-server:1.0.0
    ports:
      - "8761:8761"
    networks:
      - spring-network
  api-gateway:
    image: daiven75/api-gateway:1.0.0
    ports:
      - "8765:8765"
    depends_on:
      - naming-server
    environment:
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka
      - SPRING.ZIPKIN.BASEURL=http://zipkin-server:9411/
    networks:
      - spring-network
  cambio-service:
    image: daiven75/cambio-service
    restart: always
    build:
      context: .
      dockerfile: cambio-service/Dockerfile
    environment:
      - TZ=America/Sao_Paulo
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka
      - SPRING.ZIPKIN.BASEURL=http://zipkin-server:9411/
      - SPRING.APPLICATION.NAME=cambio-service
      - SPRING.DATASOURCE.URL=jdbc:mysql://cambio-db:3308/cambio_service?useTimezone=true&serverTimezone=UTC
      - SPRING.DATASOURCE.USERNAME=root
      - SPRING.DATASOURCE.PASSWORD=root
      - SPRING.FLYWAY.URL=jdbc:mysql://cambio-db:3308/cambio_service?useTimezone=true&serverTimezone=UTC
      - SPRING.FLYWAY.USER=root
      - SPRING.FLYWAY.PASSWORD=root
    ports:
      - "8000:8000"
    depends_on:
      - naming-server
      - cambio-db
    networks:
      - spring-network
  book-service:
    image: daiven75/book-service
    restart: always
    build:
      context: .
      dockerfile: book-service/Dockerfile
    environment:
      - TZ=America/Sao_Paulo
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka
      - SPRING.ZIPKIN.BASEURL=http://zipkin-server:9411/
      - SPRING.APPLICATION.NAME=book-service
      - SPRING.DATASOURCE.URL=jdbc:mysql://book-db:3310/book_service?useTimezone=true&serverTimezone=UTC
      - SPRING.DATASOURCE.USERNAME=root
      - SPRING.DATASOURCE.PASSWORD=root
      - SPRING.FLYWAY.URL=jdbc:mysql://book-db:3310/book_service?useTimezone=true&serverTimezone=UTC
      - SPRING.FLYWAY.USER=root
      - SPRING.FLYWAY.PASSWORD=root
    ports:
      - "8100:8100"
    depends_on:
      - naming-server
      - book-db
    networks:
      - spring-network
networks:
  spring-network:
    driver: bridge
volumes:
  db-data-cambio:
  db-data-book:
