name: Continuous Integration with Github

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Setup Java JDK
        uses: actions/setup-java@v3.0.0
        with:
          java-version: '17' 
          distribution: 'adopt'
          
      - name: Build Cambio Microservice Jar
        working-directory: ./cambio-service
        run: mvn clean package -DskipTests
      
      - name: Check Exists Cambio Microservice Jar
        working-directory: ./cambio-service/target
        run: echo "::set-output name=ls::$(ls)\n"
      
      - name: Build Naming Server Docker Image
        working-directory: ./naming-server
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build API Gateway Docker Image
        working-directory: ./api-gateway
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build Book Microservice Jar
        working-directory: ./book-service
        run: mvn clean package -DskipTests
        
      - name: Docker Compose Build
        working-directory: .
        run: docker-compose build
      
      - name: Push to Docker Hub
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/naming-server:1.0.0 ${{ secrets.DOCKER_USERNAME }}/naming-server:latest
          docker tag ${{ secrets.DOCKER_USERNAME }}/api-gateway:1.0.0 ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
          docker tag ${{ secrets.DOCKER_USERNAME }}/cambio-service:latest ${{ secrets.DOCKER_USERNAME }}/cambio-service:latest
          docker tag ${{ secrets.DOCKER_USERNAME }}/book-service:latest ${{ secrets.DOCKER_USERNAME }}/book-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/naming-server:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cambio-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/book-service:latest
